#!/bin/bash

# GNU General Public License v3.0
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <exported_firefox_logins.csv> > output.csv" >&2
    exit 1
fi

csv_file_name=$1

echo "Group;Title;Username;Password;URL;Notes"

tail -n +2 "$csv_file_name" | while IFS=, read -r url username password httpRealm formActionOrigin guid timeCreated timeLastUsed timePasswordChanged; do
    url=$(echo "$url" | tr -d '"')
    username=$(echo "$username" | tr -d '"')
    password=$(echo "$password" | tr -d '"')
    timeCreated=$(echo "$timeCreated" | tr -d '"')
    timestamp=$(date -d "@$((timeCreated / 1000))" -Iseconds)

    echo "Firefox;$url;$username;$password;$url;$timestamp"
done
